### ISSUE TITLE
检查点数据异常导致数据无效

### ISSUE THREAD

**Issue by 598597535** [FengLi666/sports#8]
没错，又是我，这次是没过3个检查点导致数据无效

**Comment by astronaut0131** [comment]
https://github.com/FengLi666/sports/blob/2290558a0a76fa4cb1f3ea3a8e3598e9960104aa/mysports/no_free_run.py#L24
https://github.com/FengLi666/sports/blob/2290558a0a76fa4cb1f3ea3a8e3598e9960104aa/mysports/no_free_run.py#L25
把`[:red]`和`[:green]`去了试试 不行就没啥办法了 app本身问题

**Comment by 598597535** [comment]
Traceback (most recent call last):
  File "mysports\run.py", line 19, in run
  File "mysports\no_free_run.py", line 14, in no_free_run
KeyError: 'data'
run failed
运行的时候出现这个了

**Comment by astronaut0131** [comment]
10点以后不能跑步了 明天再玩吧 (

**Comment by 598597535** [comment]
版本更新不能用了吗

**Comment by mortredlw** [comment]
现在不能用了吗

**Comment by astronaut0131** [comment]
最近没怎么维护过 如果不能用可以新开个issue具体说下报错 每天晚上10点以后是没法用的
